package iter

func Adjacent()                            {}
func All_equal()                           {}
func All_unique()                          {}
func Always_iterable()                     {}
func Always_reversible()                   {}
func Before_and_after()                    {}
func Bucket()                              {}
func Callback_iter()                       {}
func Chunked()                             {}
func Chunked_even()                        {}
func Circular_shifts()                     {}
func Collapse()                            {}
func Collate()                             {}
func Combination_index()                   {}
func Consecutive_groups()                  {}
func Consume()                             {}
func Consumer()                            {}
func Convolve()                            {}
func Count_cycle()                         {}
func Countable()                           {}
func Difference()                          {}
func Distinct_combinations()               {}
func Distinct_permutations()               {}
func Distribute()                          {}
func Divide()                              {}
func Dotproduct()                          {}
func Duplicates_everseen()                 {}
func Duplicates_justseen()                 {}
func Exactly_n()                           {}
func Filter_except()                       {}
func First()                               {}
func First_true()                          {}
func Flatten()                             {}
func Groupby_transform()                   {}
func Grouper()                             {}
func Ichunked()                            {}
func Iequals()                             {}
func Ilen()                                {}
func Interleave()                          {}
func Interleave_evenly()                   {}
func Interleave_longest()                  {}
func Intersperse()                         {}
func Is_sorted()                           {}
func Islice_extended()                     {}
func Iter_except()                         {}
func Iterate()                             {}
func Last()                                {}
func Locate()                              {}
func Longest_common_prefix()               {}
func Lstrip()                              {}
func Make_decorator()                      {}
func Map_except()                          {}
func Map_if()                              {}
func Map_reduce()                          {}
func Mark_ends()                           {}
func Minmax()                              {}
func More()                                {}
func Ncycles()                             {}
func Nth()                                 {}
func Nth_combination()                     {}
func Nth_or_last()                         {}
func Nth_permutation()                     {}
func Nth_product()                         {}
func Numeric_range()                       {}
func One()                                 {}
func Only()                                {}
func Pad_none()                            {}
func Padded()                              {}
func Padnone()                             {}
func Pairwise()                            {}
func Partition()                           {}
func Partitions()                          {}
func Peekable()                            {}
func Permutation_index()                   {}
func Powerset()                            {}
func Prepend()                             {}
func Product_index()                       {}
func Quantify()                            {}
func Raise_()                              {}
func Random_combination()                  {}
func Random_combination_with_replacement() {}
func Random_permutation()                  {}
func Random_product()                      {}
func Recipes()                             {}
func Repeat_each()                         {}
func Repeat_last()                         {}
func Repeatfunc()                          {}
func Replace()                             {}
func Rlocate()                             {}
func Roundrobin()                          {}
func Rstrip()                              {}
func Run_length()                          {}
func sample()                              {}
func seekable()                            {}
func Set_partitions()                      {}
func Side_effect()                         {}
func Sliced()                              {}
func Sliding_window()                      {}
func Sort_together()                       {}
func Split_after()                         {}
func Split_at()                            {}
func Split_before()                        {}
func Split_into()                          {}
func Split_when()                          {}
func Spy()                                 {}
func Stagger()                             {}
func Strictly_n()                          {}
func Strip()                               {}
func Subslices()                           {}
func Substrings()                          {}
func Substrings_indexes()                  {}
func Tabulate()                            {}
func Tail()                                {}
func Take()                                {}
func Time_limited()                        {}
func Triplewise()                          {}
func Unique_everseen()                     {}
func Unique_in_window()                    {}
func Unique_justseen()                     {}
func Unique_to_each()                      {}
func Unzip()                               {}
func Value_chain()                         {}
func Windowed()                            {}
func Windowed_complete()                   {}
func With_iter()                           {}
func Zip_broadcast()                       {}
func Zip_equal()                           {}
func Zip_offset()                          {}
